server:
  location: https://localhost
  address: 0.0.0.0
  port: 9443
  ssl:
    enabled: true
    key-alias: testserver
    key-password: changeit
    key-store: classpath:privateKey.store
    key-store-password: changeit
    
rest:
  serviceUsername: admin
  servicePassword: admin
  
spring:
  redis:
    port: 6379
    host: localhost
    
ldap:
  port: 10389
  url: ldap://localhost:10389
  searchBase: dc=springframework,dc=org
  userBase: ou=users
  groupBase: ou=groups
  bindDn: uid=admin
  bindPassword: password
  uidNumber:
    start: 10000000
    end: 11000000
  gidNumber:
    start: 10000000
    end: 11000000
  default:
    gidNumber: 600000
